#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateManagement.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="master")]
	public partial class MVCDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MVCDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MVCDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MVCDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MVCDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Delete_On_Employee")]
		public int Delete_On_Employee([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> emp_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), emp_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Insert_On_Department")]
		public int Insert_On_Department([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dp_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dp_location)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dp_name, dp_location);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Insert_On_Employee")]
		public int Insert_On_Employee([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(75)")] string emp_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,2)")] System.Nullable<decimal> emp_salary, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> emp_age, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> emp_dp_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), emp_name, emp_salary, emp_age, emp_dp_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Select_On_EmpDpt")]
		public ISingleResult<Select_On_EmpDptResult> Select_On_EmpDpt([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> emp_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> isActive)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), emp_id, isActive);
			return ((ISingleResult<Select_On_EmpDptResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Update_On_Employee")]
		public int Update_On_Employee([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> emp_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(75)")] string emp_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,2)")] System.Nullable<decimal> emp_salary, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> emp_age, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> emp_dp_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), emp_id, emp_name, emp_salary, emp_age, emp_dp_id);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class Select_On_EmpDptResult
	{
		
		private int _emp_id;
		
		private string _emp_name;
		
		private System.Nullable<decimal> _emp_salary;
		
		private int _emp_age;
		
		private string _dp_name;
		
		private string _dp_location;
		
		public Select_On_EmpDptResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_id", DbType="Int NOT NULL")]
		public int emp_id
		{
			get
			{
				return this._emp_id;
			}
			set
			{
				if ((this._emp_id != value))
				{
					this._emp_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_name", DbType="VarChar(75) NOT NULL", CanBeNull=false)]
		public string emp_name
		{
			get
			{
				return this._emp_name;
			}
			set
			{
				if ((this._emp_name != value))
				{
					this._emp_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_salary", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> emp_salary
		{
			get
			{
				return this._emp_salary;
			}
			set
			{
				if ((this._emp_salary != value))
				{
					this._emp_salary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_age", DbType="Int NOT NULL")]
		public int emp_age
		{
			get
			{
				return this._emp_age;
			}
			set
			{
				if ((this._emp_age != value))
				{
					this._emp_age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dp_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string dp_name
		{
			get
			{
				return this._dp_name;
			}
			set
			{
				if ((this._dp_name != value))
				{
					this._dp_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dp_location", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string dp_location
		{
			get
			{
				return this._dp_location;
			}
			set
			{
				if ((this._dp_location != value))
				{
					this._dp_location = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
