#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateManagement.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="master")]
	public partial class PersonDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPERSON(PERSON instance);
    partial void UpdatePERSON(PERSON instance);
    partial void DeletePERSON(PERSON instance);
    #endregion
		
		public PersonDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		

		// PERSONs is table on which we perform all the operations using linq.
		public System.Data.Linq.Table<PERSON> PERSONs
		{
			get
			{
				return this.GetTable<PERSON>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PERSON")]
	public partial class PERSON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _p_id;
		
		private string _p_fname;
		
		private string _p_mname;
		
		private string _p_lname;
		
		private int _p_age;
		
		private System.DateTime _p_dob;
		
		private char _p_gender;
		
		private System.Nullable<decimal> _p_salary;
		
		private string _p_photo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onp_idChanging(int value);
    partial void Onp_idChanged();
    partial void Onp_fnameChanging(string value);
    partial void Onp_fnameChanged();
    partial void Onp_mnameChanging(string value);
    partial void Onp_mnameChanged();
    partial void Onp_lnameChanging(string value);
    partial void Onp_lnameChanged();
    partial void Onp_ageChanging(int value);
    partial void Onp_ageChanged();
    partial void Onp_dobChanging(System.DateTime value);
    partial void Onp_dobChanged();
    partial void Onp_genderChanging(char value);
    partial void Onp_genderChanged();
    partial void Onp_salaryChanging(System.Nullable<decimal> value);
    partial void Onp_salaryChanged();
    partial void Onp_photoChanging(string value);
    partial void Onp_photoChanged();
    #endregion
		
		public PERSON()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int p_id
		{
			get
			{
				return this._p_id;
			}
			set
			{
				if ((this._p_id != value))
				{
					this.Onp_idChanging(value);
					this.SendPropertyChanging();
					this._p_id = value;
					this.SendPropertyChanged("p_id");
					this.Onp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string p_fname
		{
			get
			{
				return this._p_fname;
			}
			set
			{
				if ((this._p_fname != value))
				{
					this.Onp_fnameChanging(value);
					this.SendPropertyChanging();
					this._p_fname = value;
					this.SendPropertyChanged("p_fname");
					this.Onp_fnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_mname", DbType="VarChar(50)")]
		public string p_mname
		{
			get
			{
				return this._p_mname;
			}
			set
			{
				if ((this._p_mname != value))
				{
					this.Onp_mnameChanging(value);
					this.SendPropertyChanging();
					this._p_mname = value;
					this.SendPropertyChanged("p_mname");
					this.Onp_mnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string p_lname
		{
			get
			{
				return this._p_lname;
			}
			set
			{
				if ((this._p_lname != value))
				{
					this.Onp_lnameChanging(value);
					this.SendPropertyChanging();
					this._p_lname = value;
					this.SendPropertyChanged("p_lname");
					this.Onp_lnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_age", DbType="Int NOT NULL")]
		public int p_age
		{
			get
			{
				return this._p_age;
			}
			set
			{
				if ((this._p_age != value))
				{
					this.Onp_ageChanging(value);
					this.SendPropertyChanging();
					this._p_age = value;
					this.SendPropertyChanged("p_age");
					this.Onp_ageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_dob", DbType="Date NOT NULL")]
		public System.DateTime p_dob
		{
			get
			{
				return this._p_dob;
			}
			set
			{
				if ((this._p_dob != value))
				{
					this.Onp_dobChanging(value);
					this.SendPropertyChanging();
					this._p_dob = value;
					this.SendPropertyChanged("p_dob");
					this.Onp_dobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_gender", DbType="Char(1) NOT NULL")]
		public char p_gender
		{
			get
			{
				return this._p_gender;
			}
			set
			{
				if ((this._p_gender != value))
				{
					this.Onp_genderChanging(value);
					this.SendPropertyChanging();
					this._p_gender = value;
					this.SendPropertyChanged("p_gender");
					this.Onp_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_salary", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> p_salary
		{
			get
			{
				return this._p_salary;
			}
			set
			{
				if ((this._p_salary != value))
				{
					this.Onp_salaryChanging(value);
					this.SendPropertyChanging();
					this._p_salary = value;
					this.SendPropertyChanged("p_salary");
					this.Onp_salaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_photo", DbType="VarChar(100)")]
		public string p_photo
		{
			get
			{
				return this._p_photo;
			}
			set
			{
				if ((this._p_photo != value))
				{
					this.Onp_photoChanging(value);
					this.SendPropertyChanging();
					this._p_photo = value;
					this.SendPropertyChanged("p_photo");
					this.Onp_photoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
